import type { Course } from './types';

export const courses: Course[] = [
  {
    id: 'debt-elimination-101',
    title: 'Debt Elimination 101',
    description: 'Create a sustainable plan to eliminate debt without extreme lifestyle changes.',
    longDescription: 'This course provides a step-by-step guide to understanding your debt, creating a realistic payoff strategy, and staying motivated. You\'ll learn about different debt-tackling methods like the snowball and avalanche techniques, how to negotiate with creditors, and ways to increase your income to accelerate your journey to being debt-free.',
    duration: '2 hours',
    price: 47,
    category: 'Debt',
    format: 'Video',
    imageId: 'course-1',
  },
  {
    id: 'investment-basics',
    title: 'Investment Basics for Beginners',
    description: 'Learn the fundamentals of investing to build long-term wealth.',
    longDescription: 'Demystify the world of investing with this beginner-friendly course. We cover stocks, bonds, mutual funds, and ETFs. You\'ll learn how to open a brokerage account, understand risk tolerance, and build a diversified portfolio that aligns with your financial goals. No prior experience needed!',
    duration: '3 hours',
    price: 67,
    category: 'Investing',
    format: 'Video',
    imageId: 'course-2',
  },
  {
    id: 'budgeting-for-variable-income',
    title: 'Budgeting for Variable Income',
    description: 'Develop sustainable financial practices for a fluctuating income.',
    longDescription: 'Perfect for freelancers, entrepreneurs, and commission-based professionals. This course teaches you how to create a flexible budget that adapts to your income swings. Learn how to manage cash flow, prioritize expenses, and build a financial safety net when your paycheck isn\'t consistent.',
    duration: '1.5 hours',
    price: 37,
    category: 'Budgeting',
    format: 'Video',
    imageId: 'course-3',
  },
  {
    id: 'building-an-emergency-fund',
    title: 'Building an Emergency Fund',
    description: 'Create a financial safety net to protect you from unexpected life events.',
    longDescription: 'Life is unpredictable. An emergency fund is your first line of defense against job loss, medical emergencies, or unexpected repairs. This course guides you on how much to save, where to keep your fund for safety and accessibility, and strategies to build it faster.',
    duration: '1 hour',
    price: 27,
    category: 'Budgeting',
    format: 'Text',
    imageId: 'course-4',
  },
  {
    id: 'understanding-credit',
    title: 'Understanding & Improving Your Credit',
    description: 'Master your credit score to unlock better financial opportunities.',
    longDescription: 'Your credit score impacts everything from loan rates to insurance premiums. Learn what makes up your score, how to read your credit report, and actionable strategies to improve your creditworthiness. We will also cover how to dispute errors and protect yourself from identity theft.',
    duration: '2.5 hours',
    price: 47,
    category: 'Debt',
    format: 'Video',
    imageId: 'course-5',
  },
  {
    id: 'tax-implications-for-freelancers',
    title: 'Tax Implications for Freelancers',
    description: 'Navigate the complexities of self-employment taxes with confidence.',
    longDescription: 'Don\'t get caught by surprise at tax time. This course covers the essentials of freelancer taxes, including tracking income and expenses, understanding quarterly estimated taxes, identifying deductible business expenses, and setting up retirement accounts like a SEP IRA or Solo 401(k).',
    duration: '2 hours',
    price: 57,
    category: 'Budgeting',
    format: 'Text',
    imageId: 'course-6',
  },
];
